### ISSUE TITLE
KeyError: 'driver' or 'screenshot'

### ISSUE THREAD

**Issue by afperezp** [clemfromspace/scrapy-selenium#74]
hey i just started to scrape with scrapy-selenium but
![Bildschirmfoto 2020-09-14 um 11 11 24](https://user-images.githubusercontent.com/31297615/93067136-1d3a6d00-f67b-11ea-895c-4d240e0df678.png)
 i am always getting this same problem. My mentor suggested adding Webdriver to the path, but the problem is not fixed, any suggestions?

**Comment by tristanlatr** [comment]
What's your code ?

**Comment by uselessvevo** [comment]
Same thing. Can't access `response.meta['screenshot'] or 'driver'` in my middleware

**Comment by raghavsehgal1** [comment]
I'm facing the same issue. As requested by @tristanlatr above, here's my code -


    `import scrapy
     from scrapy_selenium import SeleniumRequest
     from selenium import webdriver
     from shutil import which
     import requests
    
     

      class LinkedinCrawlerSpider(scrapy.Spider):
              name = 'linkedin_crawler'
              allowed_domains = ['www.linkedin.com']
    
    
        def start_requests(self):
            yield SeleniumRequest(
                url = 'https://www.linkedin.com/sales/login',
                wait_time = 5,
                callback = self.login
            )
        def login(self, response):
    
            print(response.request.meta['driver'].title)`

Screenshot of the error - 

<img width="1033" alt="Screenshot 2020-12-22 at 1 12 27 PM" src="https://user-images.githubusercontent.com/53180942/102862639-66a70f00-4457-11eb-8394-31db84cec4e3.png">

**Comment by tristanlatr** [comment]
@raghavsehgal1 Did you activate the downloader middleware in the settings.py ?

**Comment by raghavsehgal1** [comment]
@tristanlatr Yes, I did. scrapy-selenium related Code snippet from settings.py -


       DOWNLOADER_MIDDLEWARES = {
                      'scrapy_selenium.SeleniumMiddleware': 800
                  }
      
      from shutil import which
      
      SELENIUM_DRIVER_NAME = 'chrome'
      SELENIUM_DRIVER_EXECUTABLE_PATH = which('chromedriver')
      SELENIUM_DRIVER_ARGUMENTS=['--headless']  # '--headless' if using chrome instead of firefox

I have been trying multiple approaches but I have been unable to figure out why the issue persists. I tried to print the meta object without any keys. This is the object that was printed -

{'download_timeout': 180.0, 'download_slot': 'golden.com', 'download_latency': 0.34168577194213867}

**Comment by blackwhiteman** [comment]
I had a similar issue and was resolved by making sure driver arguments is set to ['--headless'] i.e. two dashes for chrome

**Comment by Lpaydat** [comment]
I had the same issue, it turned out that I don't have the driver installed. (it's says in the log that the driver name and driver path is not set, so the selenium middleware is disable)

The issue solved after install the `chromedriver` or  `geckodriver`.

Hope this help.

**Comment by tomato-ga** [comment]
I had the same issue.
I get this error when debugging, but the code seems to be working fine.

**Comment by mahmoudodoo** [comment]
> ['--headless']
Hi @blackwhiteman 
It's still the same issue i changed as the following:
SELENIUM_DRIVER_NAME = "chrome"
SELENIUM_DRIVER_EXECUTABLE_PATH = '/drivers/chromedriver'
SELENIUM_DRIVER_ARGUMENTS = ['--headless']
